### ISSUE TITLE
Issue with orders

### ISSUE THREAD

**Issue by krazzarkov** [dineshpinto/orderbook-delta-bot#1]
Hello,

I randomly stumbled across your repo and wanted to test out your implementation. Unfortunately, when I ran the bot, I experienced a few errors.

When I first set it up, I got an error saying "Unable to place order, Err: API("Invalid reduce-only order"). 
![image](https://user-images.githubusercontent.com/8461672/163117852-4c421f26-a871-417f-b947-68fd07ca1dc6.png)

To fix this, I set `reduce-only` to `false` in order_handler.rs which seemed to fix the issue.

Unfortunately, I also encountered a second problem which occurs after the bot initially takes a trade where it is unable to set a take-profit and stop-loss order and spits out the following error:
![image](https://user-images.githubusercontent.com/8461672/163118258-a8449a16-97ae-4f0d-94cd-198db2f1f663.png)

This one, I'm not sure how to fix. Haven't had too much time to dive into the code. If you have any tips or suggestions please let me know. Any help would be greatly appreciated, thank you in advance :)

**Comment by dineshpinto** [comment]
Hey, 

It looks like some defaults got left in the code when testing. They should be fixed in the latest commit, let me know if it works for you...

The bot is still very much a work in progress, and a lot of features remain to be implemented. 

Thanks for trying it out :)
