### ISSUE TITLE
Issue with other pairs than BTC/ETH

### ISSUE THREAD

**Issue by Pusherman2** [dineshpinto/orderbook-delta-bot#2]
Hi there,

I noticed when using other pairs other than BTC/ETH, it will give the following error:
`[2022-06-01T17:23:08Z INFO  orderbook_delta_bot] The bot is not running live, no orders will be placed
thread 'main' panicked at 'Multiplication overflowed'`

Maybe it has to do with the precision required for each pair? What can we edit or adjust to be able to run for other pairs?

Kind regards.

**Comment by dineshpinto** [comment]
Hey, 

It looks like it was unable to compute the order size for altcoins with non-fractional order sizes (eg. SHIB).
I've fixed this in the latest commit.

Thanks for raising the issue :)

Cheers

**Comment by Pusherman2** [comment]
Hi there,

Thank you for your reply and commit, much appreciated. However, I noticed it currently works with SHIB but not for example with GMT/SOL. Is there something else which needs to be changed to allow for those pairs?

Kind regards.

**Comment by dineshpinto** [comment]
Hey, 

Thanks for reporting it.
This was an issue with the price precision. I put in a bug fix for it for the time being, and it works. But I'm not very happy with it.

I will look into rewriting this section once I get more familiar with the behavior of the `Decimal` crate

Cheers
